name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release for ${{ matrix.target }}
    runs-on: windows-latest
    permissions:
      contents: write
    
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          #- i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target ${{ matrix.target }}
          
      - name: Create/Update Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/${{ matrix.target }}/release/*.exe
          tag: latest
          name: "Latest Build (${{ github.sha }})"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
